services:
  web:
    container_name: task_manager_web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - TZ=America/Fortaleza
  prometheus:
    image: prom/prometheus
    container_name: task_manager_prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: task_manager_grafana
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus