name: TaskManager DevSecOps Pipeline

on:
  push:
    - main
    - stage
    - dev
  pull_request:
    branches: 
      - main
      - stage

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalando python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Instalação de dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes com cobertura
        run: pytest --cov-report=xml

      # - name: SonarQube scan
      #   uses: sonarsource/sonarqube-scan-action@v6
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  sast:
    runs-on: ubuntu-latest
    permissions:
        # Required for all workflows
        security-events: write
        # Only required for workflows in private repositories
        actions: read
        contents: read
    steps:
      - name: Verificando o repositório
        uses: actions/checkout@v4

      - name: Definindo a versão do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Instalando Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Iniciando Scan do Bandit
        # Scans the package directory; change `todo_project` if needed
        run: |
          # Show human-readable report in the console
          bandit -r todo_project -f txt || true
          # Also produce machine-readable JSON and save while showing it
          bandit -r todo_project -f json | tee bandit.json || true

      - name: Uploado do relatório do Bandit
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit.json